services:
  paperboy:
    restart: always
    network_mode: host
    build:
      context: ./paperboy
      dockerfile: ./Dockerfile
    container_name: paperboy
    volumes:
      - ./paperboy/paperboy:/app/paperboy:ro
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
    env_file:
      - .env
    command: poetry run python -m paperboy.main

  telegram-bot-api:
    restart: always
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    env_file:
      - .env
    environment:
      TELEGRAM_LOCAL: "1"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data:
